public-key: '/home/vi3/Faks/Bezbednost/siem/djangocenter/center/mini_parser/certs/public-sysqo.key'
private-key: '/home/vi3/Faks/Bezbednost/siem/djangocenter/center/mini_parser/certs/sysqo.key'
passphrase: 'sysqo'