# Generated by Django 2.0.5 on 2018-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('find_logs', 'Get Logs'), ('create_alarm', 'Create Alarm'), ('update_alarm', 'Update Alarm'), ('delete_alarm', 'Delete Alarm'), ('get_alarms', 'Get Alarms'), ('get_alarm_details', 'Get Alarm Details'), ('get_log_analytics', 'Get Log Analytics'), ('get_alarm_analytics', 'Get Alarm Analytics')),
                'managed': False,
            },
        ),
    ]
