# Generated by Django 2.0.5 on 2018-06-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20180605_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisije',
            options={'managed': False, 'permissions': (('find_logs', 'Get Logs'), ('create_alarm', 'Create Alarm'), ('update_alarm', 'Update Alarm'), ('delete_alarm', 'Delete Alarm'), ('get_alarms', 'Get Alarms'), ('get_alarm_details', 'Get Alarm Details'), ('get_log_analytics', 'Get Log Analytics'), ('get_alarm_analytics', 'Get Alarm Analytics'), ('get_hosts', 'Get Hosts'))},
        ),
    ]
