general:
#  patterns:
#    - '^a'
#    - '.*c.*'
#    - 'b+$'
#    - '^\.+'
  interval: 0.5
specific:
  directories:
    - directory:
        path: '.'
        patterns:
          - '^d'
          - '.*e.*'
          - 'f+$'
          - '^\.+'
        interval: 1
        only_specified_files: True
        files:
          - file:
              path: 'log.txt'
              patterns:
                - '^g'
                - '.*h.*'
                - 'i+$'
                - '^\.+'
              interval: 2
          - file:
              path: 'log1.txt'
              patterns:
                - '^j'
                - '.*k.*'
                - 'l+$'
                - '^\.+'
              interval: 4
    - directory:
        path: '../logGeneratorAgent'
        patterns:
          - '.*POST.*'
          - '.*DELETE.*'
        interval: 1
        only_specified_files: True
        files:
          - file:
              path: 'web_app_log20180401-025505.log'