general:
#  patterns:
#    - '^a'
#    - '.*c.*'
#    - 'b+$'
#    - '^\.+'
  interval: 0.5
specific:
  directories:
#    - directory:
#        path: '.'
#        patterns:
#          - '^d'
#          - '.*e.*'
#          - 'f+$'
#          - '^\.+'
#        interval: 1
#        only_specified_files: True
#        files:
#          - file:
#              path: 'log.txt'
#              patterns:
#                - '^g'
#                - '.*h.*'
#                - 'i+$'
#                - '^\.+'
#              interval: 2
#          - file:
#              path: 'log1.txt'
#              patterns:
#                - '^j'
#                - '.*k.*'
#                - 'l+$'
#                - '^\.+'
#              interval: 4
#    - directory:
#        path: '../logGeneratorAgent'
#        patterns:
#          - '.*POST.*'
#          - '.*DELETE.*'
#        interval: 1
#        only_specified_files: True
#        files:
#          - file:
#              path: 'web_app_log20180401-202053.log'
#              read_all: False
os:
  linux:
    only_specified_files: True
    read_all: True
    interval: 1
    directories:
      - directory:
          path: '/var/log/'
          files:
              - file:
                  path: 'wtmp.1'
              - file:
                  path: 'lastlog'
#              - file:
#                  path: 'btmp'  # problem sa permission denied
      - directory:
          path: '/var/run/'
          files:
              - file:
                  path: 'utmp'

