security:
  key: 'certs/agent_vlada2.key'
  cert: 'certs/agent_vlada.crt'
  ca: 'certs/ca.crt'
  interval: 1
  API_ENDPOINT: 'https://192.168.0.18:8443/logger'
  HOST: '192.168.0.17'
  PORT: 33333
#  PORT: 55555

  communication_protocol: 'TCP'
general:
#  patterns:
#    - '^a'
#    - '.*c.*'
#    - 'b+$'
#    - '^\.+'
  interval: 0.5
specific:
  directories:
#    - directory:
#        path: '.'
#        patterns:
#          - '^d'
#          - '.*e.*'
#          - 'f+$'
#          - '^\.+'
#        interval: 1
#        only_specified_files: True
#        files:
#          - file:
#              path: 'log.txt'
#              patterns:
#                - '^g'
#                - '.*h.*'
#                - 'i+$'
#                - '^\.+'
#              interval: 2
#          - file:
#              path: 'log1.txt'
#              patterns:
#                - '^j'
#                - '.*k.*'
#                - 'l+$'
#                - '^\.+'
#              interval: 4


   #Generator skripta
    - directory:
        path: '../logGeneratorAgent'
        patterns:
          - '.*POST.*'
          - '.*DELETE.*'
        interval: 1
        only_specified_files: True
        files:
          - file:
              path: 'web_app_log20180628-205809.log'
              read_all: False
              parser_type: 'SyslogRFC5424Parser'
    # Django i daphne
    - directory:
        path: '/home/vi3/Faks/Bezbednost/siem/djangocenter/log'
        interval: 1
        only_specified_files: True
        files:
          - file:
              path: 'daphne.log'
              read_all: True
              parser_type: 'DummyParser'
    # PostgreSQL
    - directory:
        path: '/var/log/postgresql'
        interval: 3
        only_specified_files: True
        files:
          - file:
              path: 'postgresql-10-main.log'
              read_all: True
              parser_type: 'DummyParser'
    # Nginx
    - directory:
        path: '/var/log/nginx'
        interval: 3
        only_specified_files: True
        files:
          - file:
              path: 'access.log'
              read_all: True
              parser_type: 'DummyParser'
          - file:
              path: 'error.log'
              read_all: True
              parser_type: 'DummyParser'


os:
  linux:
    only_specified_files: True
    read_all: True
    interval: 10
    directories:
      - directory:
          path: '/var/log/'
          files:
              - file:
                  path: 'tallylog'
              - file:
                  path: 'faillog'
              - file:
                  path: 'ufw.log'
                  parser_type: 'LinuxStandardSyslogParser'
              - file:
                  path: 'syslog'
              - file:
                  path: 'kern.log'
              - file:
                  path: 'wtmp'
              - file:
                  path: 'lastlog'
              - file:
                  path: 'btmp'  # problem sa permission denied
              - file:
                  path: 'auth.log'
                  parser_type: 'LinuxStandardSyslogParser'
      - directory:
          path: '/var/run/'
          only_specified_files: True
          files:
              - file:
                  path: 'utmp'
  windows:
    logs:
    - log:
        name: 'Application'
        interval: 30
        patterns:
          - '.*Disk.*'
          - '.*Battery.*'
    - log:
        name: 'System'
        interval: 20
    - log:
        name: 'Security'
        interval: 10
