logs:
    - log:
        name: 'Application'
        interval: 10
#        patterns:
#          - '.*Disk.*'
#          - '.*Battery.*'
    - log:
        name: 'System'
        interval: 15
    - log:
        name: 'Security'
        interval: 5